### PR TITLE
upgrade execa

### PR DESCRIPTION
**Pull request by est271**
- [ ] fixes issue #259 

some packages still depend on execa 0.7.0

### CODE REVIEW

**Comment by est271** [comment]
@splashinn I just noticed that starting a newline in the Text field will result in a "D with stroke" character being inserted.

**Comment by est271** [comment]
input

**Comment by est271** [comment]
result

**Comment by est271** [comment]
I am not sure if this is a result of me updating execa, but just to make sure I am going to close this pull request.

**Comment by splashinn** [comment]
@est271 okay, thank you. I will do some testing to see if it was indeed a result of updating execa.

**Pull request closed without merging**
